### ISSUE TITLE
Amatic SC font does not include latin-ext unicode range

### ISSUE THREAD

**Issue by bancek** [NUKnightLab/TimelineJS-Wordpress-Plugin#43]
On one of the pages that uses your Timeline I've noticed that non-latin characters are not displayed correctly. The problem is that your custom font definition for Amatic SC font does not include latin-ext variant.

https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1Ovu5cVuGEVp1uRpKdAaRZ7wlxX9JFsCWtOqR7UA9nmQ&font=Amatic-Andika&lang=sl&initial_zoom=4&height=730

<img width="780" alt="Screenshot 2022-06-01 at 11 20 25" src="https://user-images.githubusercontent.com/367440/171372077-7b34dce1-360a-457e-b86b-5fcc527cb5e2.png">

https://cdn.knightlab.com/libs/timeline3/latest/css/fonts/font.amatic-andika.css

Google Fonts supports other variants (e.g. `latin-ext`) you would just have to add them.

https://fonts.googleapis.com/css2?family=Amatic+SC

```css
/* latin-ext */
@font-face {
  font-family: 'Amatic SC';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/amaticsc/v24/TUZyzwprpvBS1izr_vOEBOSfU5cP1V3r.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
```
